CABoard/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('board.urls', namespace="site"))
]

board/urls.py
from django.conf.urls import url
from board import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pg>\d+)/$', views.NextView, name='pagination')
]

board/models.py
import datetime
import os

from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from  django.core.files.storage import FileSystemStorage

STATIC_CUR_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'static')

upload_storage = FileSystemStorage(location=STATIC_CUR_DIR)

from django.db.models import signals
from django.template.defaultfilters import slugify

# Receive the pre_delete signal and delete the file associated with the model instance.
from django.db.models.signals import pre_delete
from django.dispatch.dispatcher import receiver

# Create your models here.
class Board(models.Model):
    user = models.ForeignKey(User)
    nome = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, blank=True, unique=True)
    descricao = models.TextField()
    data_criacao = models.DateTimeField('Submetido', default=timezone.now())
    pub_date = models.DateTimeField('Publicado', default=timezone.now())
    data_ultima_modificacao = models.DateTimeField('Modificado', default=timezone.now())
    publicado = models.BooleanField('Publicado?', default=True)

class MediaProjeto(models.Model):
    board = models.ForeignKey(Board)
    arquivo =  models.FileField(upload_to='media/upload_user', storage=upload_storage, default="media/none.jpg")
    link_site = models.CharField(max_length=1000, blank=True)
    significado = models.CharField(max_length=255, blank=False)
    data_criacao = models.DateTimeField('Submetido', default=timezone.now())
    ordem = models.IntegerField('Ordem', blank=False, default=-1)

# SIGNALS
def board_pre_save(signal, instance, sender, **kwargs):
    """Este signal gera um slug automaticamente. Ele verifica se ja existe um
    projeto com o mesmo slug e acrescenta um numero ao final para evitar
    duplicidade"""
    if not instance.slug:
        slug = slugify(instance.nome)
        novo_slug = slug
        contador = 0

        while Board.objects.filter(slug=novo_slug).exclude(id=instance.id).count() > 0:
            contador += 1
            novo_slug = '%s-%d'%(slug, contador)

        instance.slug = novo_slug

signals.pre_save.connect(board_pre_save, sender=Board)

@receiver(pre_delete, sender=MediaProjeto)
def mediaProjeto_delete(sender, instance, **kwargs):
    # Pass false so FileField doesn't save the model.
    instance.arquivo.delete(False)

@receiver(models.signals.pre_save, sender=MediaProjeto)
def mediaProjeto_auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `MediaProjeto` object is changed.
    """
    if not instance.pk:
        return False

    try:
        old_file = MediaProjeto.objects.get(pk=instance.pk).arquivo
    except MediaProjeto.DoesNotExist:
        return False

    new_file = instance.arquivo
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

board/views.py
from django.shortcuts import render
from django.views import generic
from board.models import Board
from django.core.paginator import Paginator

# Create your views here.
class IndexView(generic.ListView):
    template_name = 'boards.html'
    context_object_name = 'board'

    def get_queryset(self):
        pranchas = Board.objects.all().order_by('id').filter(publicado=True)
        p = Paginator(pranchas, 1)
        
        return {
                'prancha' : p.page(1),
                }

def NextView(request, pg):
    
    pranchas = Board.objects.all().order_by('id').filter(publicado=True)
    p = Paginator(pranchas, 1)
    
    ctx = {
        'board' : {
                    'prancha' : p.page(pg)
                  }
          }
    
    return render(request, 'boards.html', ctx)

board/templates/boards.html
{% extends "base.html" %}
{% load staticfiles %} 

{% block main %}
{% for p in  board.prancha.object_list %}
<div class="btn-group btn-group-lg float-right" role="group"
	aria-label="Basic example">
	{% if board.prancha.has_previous %}
	<button type="button" class="btn btn-primary" onclick="paginacao({{board.prancha.previous_page_number}});">
		<i class="fas fa-chevron-left"></i>
	</button>
	{% else %}
	<button type="button" class="btn btn-primary" disabled>
		<i class="fas fa-chevron-left"></i>
	</button>
	{% endif %}
	
	{% if board.prancha.has_next %}
	<button type="button" class="btn btn-primary" onclick="paginacao({{board.prancha.next_page_number}});">
		<i class="fas fa-chevron-right"></i>
	</button>
	{% else %}
	<button type="button" class="btn btn-primary" disabled>
		<i class="fas fa-chevron-right"></i>
	</button>
	{% endif %}
</div>

<h1 class="cover-heading extra-c">
	 {{p.nome}} <i class="fas fa-info-circle"
		data-toggle="tooltip" data-placement="bottom"
		title="{{p.descricao}}"></i>
</h1>

<div class="container">
	<div class="row">
		{% for imagem in p.mediaprojeto_set.all %}
			{% if forloop.counter0|divisibleby:4 %}
			</div>
			<div class="row">
			{% endif %}
			<div class="col-sm">
				<img src="{% static imagem.arquivo %}" class="rounded img-fluid d-block mb-4 fas fa-info-circle" 
					 data-sig="{{imagem.significado}}" data-toggle="tooltip" data-placement="bottom"
					 alt="{{imagem.significado}}" title="{{imagem.significado}}" />
			</div>
		{% endfor %}
	</div>
</div>

<div class="btn-group btn-group-lg float-right" role="group"
	aria-label="Basic example">
	{% if board.prancha.has_previous %}
	<button type="button" class="btn btn-primary" onclick="paginacao({{board.prancha.previous_page_number}});">
		<i class="fas fa-chevron-left"></i>
	</button>
	{% else %}
	<button type="button" class="btn btn-primary" disabled>
		<i class="fas fa-chevron-left"></i>
	</button>
	{% endif %}
	
	{% if board.prancha.has_next %}
	<button type="button" class="btn btn-primary" onclick="paginacao({{board.prancha.next_page_number}});">
		<i class="fas fa-chevron-right"></i>
	</button>
	{% else %}
	<button type="button" class="btn btn-primary" disabled>
		<i class="fas fa-chevron-right"></i>
	</button>
	{% endif %}
</div>

{% endfor %}
<div class="alert alert-info" role="alert"
	style="width: 75%; z-index: 0; display: none">
	<b>Glosa: </b> fala montada.
</div>

{% endblock %}

templates/base.html
{% load staticfiles %} 
<!doctype html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>CAPrancha</title>
	
	<!-- fontanswer -->
	<!--core first + styles last-->
	<link href="{% static 'css/web-fonts-with-css/css/fontawesome-all.css' %}" rel="stylesheet">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
	
	<script src="{% static 'js/funcionalidades.js' %}"></script>
  </head>

  <body>
	<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
		<header class="masthead mb-auto">
        <div class="inner">
          <h3 class="masthead-brand">CAPrancha</h3>
          <nav class="nav nav-masthead justify-content-center">
            <a class="nav-link active" href="#">Pranchas</a>
            <a class="nav-link" href="#">Sobre</a>
            <a class="nav-link" href="#">Contato</a>
          </nav>
        </div>
      </header>

		<main role="main" class="w-100 h-100">
		{% block main %}
		
		{% endblock %}
        </main>

		<footer class="mastfoot mt-auto text-center">
			<div class="inner">
			  <p>Aplicação por Luiz Fernando Rienoso. Template Baseado no <a href="https://getbootstrap.com/">Bootstrap</a>.</p>
			</div>
		</footer>
	</div>


    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery-3.3.1.slim.min.js' %}" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>
	window.jQuery || document.write('<script src="/static/js/vendor/jquery-slim.min.js"><\/script>');
	
	$(function () {
		$('[data-toggle="tooltip"]').tooltip();
	});
	
	</script>
    <script src="{% static 'js/vendor/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  </body>
</html>